name: central

on: 
  push:
    branches: [ "main" ]
jobs:
  data:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL }}
  data2:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL2 }}

