name: central
on: 
  push:
    branches: [ "main" ]

jobs:
  data:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL }}
  data2:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL2 }}
  data3:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL3 }}
  data4:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL4 }}
  data5:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL5 }}
  data6:
    runs-on: windows-latest
    steps: 
      - uses: actions/checkout@v4
      - name: data
        continue-on-error: true
        run: ${{ secrets.CENTRAL6 }}

